title: Klink's Links
author: Michael Klink
email: klink.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some of the awesomest links on the interwebs

# social links
twitter_username: Twitter-Sucks # DO NOT include the @ character, or else the build will fail!
github_username:  Klink-Dev # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
